#!/usr/bin/python3

import argparse


def get_parser():
    def proxy_sum(args):
	    """Fonction proxy vers la primitive sum"""
	    resultat = sum(args.nombres)
	    if args.verbose:
		    print('La somme vaut %s.' % resultat)
	    else:
		    print(resultat)

    def proxy_max(args):
	    """Fonction proxy vers la primitive max"""
	    resultat = max(args.nombres)
	    if args.verbose:
		    print('La maximum vaut %s.' % resultat)
	    else:
		    print(resultat)

    def proxy_min(args):
	    """Fonction proxy vers la primitive min"""
	    resultat = min(args.nombres)
	    if args.verbose:
		    print('La minimum vaut %s.' % resultat)
	    else:
		    print(resultat)


    parser = argparse.ArgumentParser(
	    prog = 'exemple',
	    description = """Programme permettant de sommer trouver le minimum ou le maximum""",
	    epilog = """Exemple basique"""
    )


    parser.add_argument(
	    "-v",
	    "--verbose",
	    action="store_true",
	    help="Mode bavard",
    )


    # Permettre la création des sous-analyseurs
    subparsers = parser.add_subparsers(help='Liste des commandes')

    somme_parser = subparsers.add_parser(
	    'somme',
	    description = "Faire la somme",
	    help = "Calcul de la somme",
    )

    somme_parser.add_argument(
	    'nombres',
	    help = """Nombres entiers (1 à n)""",
	    type = int,
	    nargs="+",
    )

    somme_parser.set_defaults(func=proxy_sum)

    minimum_parser = subparsers.add_parser(
	    'minimum',
	    description = "Calculer le minimum",
	    help = "Calcul du minimum",
    )

    minimum_parser.add_argument(
	    'nombres',
	    help = """Nombres entiers (1 à n)""",
	    type = int,
	    nargs="+",
    )

    minimum_parser.set_defaults(func=proxy_min)

    maximum_parser = subparsers.add_parser(
	    'maximum',
	    description = "Calculer le maximum",
	    help = "Calcul du maximum",
    )

    maximum_parser.add_argument(
	    'nombres',
	    help = """Nombres entiers (1 à n)""",
	    type = int,
	    nargs="+",
    )

    maximum_parser.set_defaults(func=proxy_max)

    return parser


if __name__ == '__main__':
    parser = get_parser()
    args = parser.parse_args()
    args.func(args)

