#!/usr/bin/python3

import argparse


def get_parser():


    parser = argparse.ArgumentParser(
	    prog = 'somme',
	    description = """Programme permettant de sommer trois entiers""",
	    epilog = """Exemple basique"""
    )

    parser.add_argument(
	    "-v",
	    "--verbose",
	    action="store_true",
	    help="Mode bavard",
    )
    parser.add_argument(
	    'un',
	    help = """Premier nombre""",
	    type = int,
    )
    parser.add_argument(
	    'deux',
	    help = """Deuxième nombre""",
	    type = int,
    )
    parser.add_argument(
	    'trois',
	    help = """Troisième nombre""",
	    type = int,
    )

    def proxy_sum(args):
	    """Fonction proxy vers la primitive sum"""
	    resultat = sum([
		    args.un,
		    args.deux,
		    args.trois,
	    ])
	    if args.verbose:
		    print('%s + %s + %s = %s.' % (args.un, args.deux, args.trois, resultat))
	    else:
		    print(resultat)

    parser.set_defaults(func=proxy_sum)

    return parser


if __name__ == '__main__':
    parser = get_parser()
    args = parser.parse_args()
    args.func(args)

