#!/usr/bin/python3

import argparse


def get_parser():
    def proxy_sum(args):
	    """Fonction proxy vers la primitive sum"""
	    resultat = sum(args.nombres)
	    if args.verbose:
		    print('La somme vaut %s.' % resultat)
	    else:
		    print(resultat)


    parser = argparse.ArgumentParser(
	    prog = 'somme',
	    description = """Programme permettant de sommer trois entiers""",
	    epilog = """Exemple basique"""
    )


    parser.add_argument(
	    "-v",
	    "--verbose",
	    action="store_true",
	    help="Mode bavard",
    )
    parser.add_argument(
	    'nombres',
	    help = """Nombres entiers (1 à n)""",
	    type = int,
	    nargs="+",
    )

    parser.set_defaults(func=proxy_sum)

    return parser


if __name__ == '__main__':
    parser = get_parser()
    args = parser.parse_args()
    args.func(args)

