#!/usr/bin/python3

import argparse

from incident import Level, Incident, Dashboard, PICKLE_FILENAME, JSON_FILENAME

def using_default_dashboard(func):
    def action(arguments):
        dashboard=Dashboard()
        dashboard.load(PICKLE_FILENAME)
        func(dashboard, arguments)
        dashboard.save(PICKLE_FILENAME)
        dashboard.save(JSON_FILENAME)
        if arguments.verbose:
            dashboard.display()
    return action


def get_parser():

    parser = argparse.ArgumentParser(
        prog='incident',
        description="""Programme permettant de gérer des incidents""",
        epilog="""Réalisé pour le livre Programmation système avec Python"""
    )

    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Mode bavard",
    )

    subparsers = parser.add_subparsers(help='Liste des commandes')

    add_parser = subparsers.add_parser(
	    'add',
	    description = "Ajouter un incident",
	    help = "Permet de rajouter un incident",
    )

    add_parser.add_argument(
        'title',
        help="Titre de l'incident",
    )

    @using_default_dashboard
    def proxy_add(dashboard, arguments):
        dashboard.add(Incident(arguments.title))

    add_parser.set_defaults(func=proxy_add)

    remove_parser = subparsers.add_parser(
        'remove',
        description="Supprimer un incident",
        help="Permet de supprimer un incident",
    )

    remove_parser.add_argument(
        'index',
        help="Indice de l'incident",
        type=int,
    )

    @using_default_dashboard
    def proxy_remove(dashboard, arguments):
        dashboard.remove(arguments.index)

    remove_parser.set_defaults(func=proxy_remove)

    display_parser = subparsers.add_parser(
        'display',
        description="Ajouter un incident",
        help="Permet de rajouter un incident",
    )

    display_parser.add_argument(
        'index',
        help="Indice de l'incident",
        type=int,
        nargs="?",
    )

    @using_default_dashboard
    def proxy_display(dashboard, arguments):
        dashboard.display(arguments.index)

    display_parser.set_defaults(func=proxy_display)

    up_parser = subparsers.add_parser(
        'up',
        description="Escalader un incident",
        help="Permet d'augmenter de 1 le niveau d'un incident",
    )

    up_parser.add_argument(
        'index',
        help="Indice de l'incident",
        type=int,
    )

    @using_default_dashboard
    def proxy_up(dashboard, arguments):
        dashboard.up(arguments.index)

    up_parser.set_defaults(func=proxy_up)

    down_parser = subparsers.add_parser(
        'down',
        description="Désscalader un incident",
        help="Permet de diminuer de 1 le niveau d'un incident",
    )

    down_parser.add_argument(
        'index',
        help="Indice de l'incident",
        type=int,
    )

    @using_default_dashboard
    def proxy_down(dashboard, arguments):
        dashboard.down(arguments.index)

    down_parser.set_defaults(func=proxy_down)

    return parser


if __name__ == '__main__':
    parser = get_parser()
    parsed_args = parser.parse_args()
    parsed_args.func(parsed_args)
